from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import io
from datetime import datetime

def generate_diagnosis_report(result):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#667eea')
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=12,
        spaceBefore=20,
        textColor=colors.HexColor('#333333')
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=8
    )
    
    elements = []
    
    elements.append(Paragraph("AI Multi-Modal Disease Detection", title_style))
    elements.append(Paragraph("Diagnostic Report", styles['Heading2']))
    elements.append(Spacer(1, 20))
    
    report_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    elements.append(Paragraph(f"<b>Report Generated:</b> {report_date}", normal_style))
    elements.append(Spacer(1, 20))
    
    elements.append(Paragraph("Diagnosis Summary", heading_style))
    
    summary_data = [
        ['Parameter', 'Value'],
        ['Final Diagnosis', str(result.get('diagnosis', 'N/A'))],
        ['Confidence Score', f"{result.get('final_confidence', 0):.2%}"],
        ['Fusion Method', str(result.get('fusion_method', 'N/A'))],
        ['Modalities Used', str(result.get('modalities_count', 0))]
    ]
    
    summary_table = Table(summary_data, colWidths=[2.5*inch, 3.5*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('TOPPADDING', (0, 1), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
        ('BOX', (0, 0), (-1, -1), 2, colors.HexColor('#667eea')),
    ]))
    
    elements.append(summary_table)
    elements.append(Spacer(1, 30))
    
    if 'modality_results' in result and result['modality_results']:
        elements.append(Paragraph("Individual Modality Results", heading_style))
        
        modality_data = [['Modality', 'Prediction', 'Confidence']]
        for mod in result['modality_results']:
            modality_data.append([
                str(mod.get('Modality', 'N/A')),
                str(mod.get('Prediction', 'N/A')),
                str(mod.get('Confidence', 'N/A'))
            ])
        
        modality_table = Table(modality_data, colWidths=[2*inch, 2.5*inch, 1.5*inch])
        modality_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#764ba2')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('TOPPADDING', (0, 1), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
        ]))
        
        elements.append(modality_table)
        elements.append(Spacer(1, 30))
    
    elements.append(Paragraph("Disclaimer", heading_style))
    disclaimer_text = """
    This report is generated by an AI-based diagnostic system for educational and screening purposes only. 
    It should not be used as a substitute for professional medical advice, diagnosis, or treatment. 
    Please consult a qualified healthcare professional for proper medical evaluation and care.
    """
    elements.append(Paragraph(disclaimer_text, normal_style))
    elements.append(Spacer(1, 20))
    
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.gray,
        alignment=TA_CENTER
    )
    elements.append(Paragraph("AI Multi-Modal Disease Detection System | Powered by Advanced Machine Learning", footer_style))
    
    doc.build(elements)
    
    buffer.seek(0)
    return buffer.getvalue()


def generate_colorblind_report(result):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=22,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#667eea')
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=12,
        spaceBefore=20,
        textColor=colors.HexColor('#333333')
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=8
    )
    
    elements = []
    
    elements.append(Paragraph("Color Blindness Assessment Report", title_style))
    elements.append(Spacer(1, 20))
    
    report_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    elements.append(Paragraph(f"<b>Assessment Date:</b> {report_date}", normal_style))
    elements.append(Spacer(1, 20))
    
    elements.append(Paragraph("Overall Assessment", heading_style))
    
    summary_data = [
        ['Parameter', 'Result'],
        ['Diagnosis', str(result.get('overall_diagnosis', 'N/A'))],
        ['CVD Type', str(result.get('cvd_type', 'N/A'))],
        ['Severity', str(result.get('severity', 'N/A'))],
        ['Eye Damage Ratio', f"{result.get('damage_percentage', 0):.1f}%"],
        ['Average Accuracy', f"{result.get('average_accuracy', 0):.1f}%"]
    ]
    
    summary_table = Table(summary_data, colWidths=[2.5*inch, 3.5*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8f9fa')),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('TOPPADDING', (0, 1), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#dee2e6')),
        ('BOX', (0, 0), (-1, -1), 2, colors.HexColor('#667eea')),
    ]))
    
    elements.append(summary_table)
    elements.append(Spacer(1, 30))
    
    elements.append(Paragraph("Disclaimer", heading_style))
    disclaimer_text = """
    This assessment is for screening purposes only and should not replace professional ophthalmological examination. 
    Please consult an eye care professional for comprehensive color vision testing and official diagnosis.
    """
    elements.append(Paragraph(disclaimer_text, normal_style))
    
    doc.build(elements)
    
    buffer.seek(0)
    return buffer.getvalue()